// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migration'lar için DOĞRUDAN (unpooled) bağlantı tercih edilir; Neon'un
    // pgbouncer'lı pooled bağlantısı migration'da sorun çıkarır. Yerelde
    // DATABASE_URL_UNPOOLED tanımsızsa DATABASE_URL'e düşer.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
